In [1]:
import pandas as pd

# Load the student dataset
df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
# Check shape and column types
print("Dataset Shape:", df.shape)
df.info()

# Check for any missing values
print("\nMissing values per column:\n", df.isnull().sum())

Dataset Shape: (1000, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

Missing values per column:
 gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [3]:
# 1. Clean column names (replace spaces and slashes with underscores, convert to lowercase)
df.columns = df.columns.str.replace(' ', '_').str.replace('/', '_').str.lower()

In [4]:

# 2. Clean text data inside columns (strip extra spaces and make lowercase)
text_cols = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
for col in text_cols:
    df[col] = df[col].str.strip().str.lower()

print("Cleaned Columns:", df.columns.tolist())
df.head()

Cleaned Columns: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score']

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group b,bachelor's degree,standard,none,72,72,74
1,female,group c,some college,standard,completed,69,90,88
2,female,group b,master's degree,standard,none,90,95,93
3,male,group a,associate's degree,free/reduced,none,47,57,44
4,male,group c,some college,standard,none,76,78,75

In [5]:
# Target columns (what we want to predict)
target_cols = ['math_score', 'reading_score', 'writing_score']

In [6]:
# X contains demographics and student background details
X = df.drop(columns=target_cols)

In [7]:
# y contains the actual test scores
y = df[target_cols]

In [8]:
print("Features (X) shape:", X.shape)
print("Targets (y) shape:", y.shape)

Features (X) shape: (1000, 5)
Targets (y) shape: (1000, 3)

In [9]:
df.to_csv('Cleaned_Students_Performance.csv', index=False)
print("Success! Cleaned data saved.")

Success! Cleaned data saved.